In [1]:
import numpy as np

## Задание 1

In [17]:
a=np.array( [[1, 6], [2, 8], [3, 11], [3, 10], [1, 7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [22]:
mean_a = a.mean(axis=0)
mean_a

array([2. , 8.4])

## Задание 2

In [48]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

## Задание 3

In [49]:
vector1 = a_centered.transpose()[0]
vector2 = a_centered.transpose()[1]
a_centered_sp = np.dot(vector1,vector2)
a_centered_sp

8.0

In [50]:
a_centered_sp / 4

2.0

## Задание 4


In [54]:
np.cov(a.T)

array([[1. , 2. ],
       [2. , 4.3]])